[build]
  # Use package.json build script. package.json already sets SKIP_LINT/DISABLE_ESLINT_PLUGIN for CI.
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Ensure Netlify environment also has these variables
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_LINT = "true"
  NODE_VERSION = "18"
  # Frontend should use the production API URL
  NEXT_PUBLIC_API_URL = "https://bobts-server-e7dxfwh7e5g9e3ad.malaysiawest-01.azurewebsites.net"

[[plugins]]
  package = "@netlify/plugin-nextjs"
