[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
  SKIP_ESLINT = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"
